# Supported ruby versions: 3, 3.0, 3-bullseye, 3.0-bullseye, 3-buster, 3.0-buster, 2, 2.7, 2-bullseye, 2.7-bullseye, 2-buster, 2.7-buster, 2.6, 2.6-bullseye, 2.6-buster
# 3.0系以外のRubyで動作検証やテストをしたい場合は3の部分を上の候補のうちのどれかに書き換えてください
FROM mcr.microsoft.com/vscode/devcontainers/ruby:3
ARG APP_HOME
ARG APP_PORT
ENV LANG C.UTF-8

ENV DEBIAN_FRONTEND noninteractive
RUN set -eux; \
  apt update && \
  apt install -y --no-install-recommends \
    bzr gsfonts imagemagick libmagick++-dev \
    ; \
  curl -sL https://deb.nodesource.com/setup_14.x | bash - && \
	apt install -y nodejs && \
	apt clean && \
	rm -rf /var/lib/apt/lists/*;
ENV DEBIAN_FRONTEND dialog

WORKDIR /var/lib/redmine
ADD . /var/lib/redmine

COPY ./.devcontainer/scripts/. /
RUN chmod +x /entrypoint.sh; \
    chmod +x /postStartCommand.sh;

RUN /postStartCommand.sh
RUN bundle update
RUN bundle install

EXPOSE $APP_PORT

ENTRYPOINT ["/entrypoint.sh"]
CMD ["/bin/bash"]
