version: '3'
services:

  # PostgreSQL
  postgresdb:
    image: postgres:14
    restart: on-failure:5
    volumes:
      - ./create-db-user.sql:/docker-entrypoint-initdb.d/create-db-user.sql
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres

  # MySQL
  # mysqldb:
  #   image: mysql:5
  #   restart: on-failure:5
  #   environment:
  #     MYSQL_ROOT_PASSWORD: password
  #     MYSQL_PASSWORD: password
  #     MYSQL_USER: db_user

  app:
    build:
      context: ..
      dockerfile: .devcontainer/Dockerfile
      args:
        APP_PORT: $APP_PORT
        # Update 'VARIANT' to pick a version of Ruby: 3, 3.1, 3.0, 2, 2.7, 2.6
        # Append -bullseye or -buster to pin to an OS version.
        # Use -bullseye variants on local arm64/Apple Silicon.
        VARIANT: "3.0-bullseye"
        # Optional Node.js version to install
        NODE_VERSION: "14"
    environment:
      RAILS_DB_ADAPTER: postgresql
      RAILS_DB_HOST: postgresdb
      RAILS_DB: app
      RAILS_DB_USERNAME: postgres
      RAILS_DB_PASSWORD: postgres
      RAILS_DB_ENCODING: utf8
      RAILS_ENV: development
    env_file: .env
    tty: true
    ports:
      - $APP_PORT:3000
    depends_on:
      - postgresdb
    #  - mysqldb
    command: sleep infinity
    volumes:
      - ..:/workspace:cached

  # For selenium test
  # chrome:
  #          M1の場合はselenium/standalone-chrome-debugが動かないため、seleniarm/standalone-chromium:latestを代わりに使うこと。
  #   image: selenium/standalone-chrome-debug:3.141.59-20210913
  #   ports:
  #   - $SELENIUM_PORT_1:4444
  #   - $SELENIUM_PORT_2:5900

  smtp:
    image: schickling/mailcatcher
    ports:
      - $MAILCATCHER_PORT:1080
