default: &default
  adapter: postgresql
  encoding: utf8
  host: <%= ENV.fetch('DB_HOST', 'localhost') %>
  port: <%= ENV.fetch('DB_PORT', '5432') %>
  username: postgres
  password: postgres

production:
  <<: *default
  database: redmine_production

development:
  <<: *default
  database: redmine_development

test:
  <<: *default
  database: redmine_test
